cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: '*.fellipecm.com'
        service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true
      - service: http_status:404
  image:
    tag: "2023.4.1"

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
